SourceToDeploy/objects/Mars_Photo__c.object
<CustomObject>
    <label>Mars Photo</label>
    <nameField>
        <label>Mars Photo Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mars Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Earth_date__c</fullName>
        <label>Earth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sol__c</fullName>
        <description>Es el valor de sol</description>
        <label>Mars days of mission</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

SourceToDeploy/classes/mPhotoController.cls
/**
 * @author            : Fernando M. Acosta P.
 * @Equipo            : CRM
 * @last modified on  : 03-22-2024
 * @last modified by  : Fernando M. Acosta P.
 * @Descripción       : Componente o clase apex ...
**/
public with sharing class mPhotoController {
    @AuraEnabled(cacheable=true)
    public static List<Mars_Photo__c> getMphotos(){
        return [SELECT Id, Name, Earth_date__c, sol__c, Image__c FROM Mars_Photo__c];
    }


}